### ISSUE TITLE
Script doesn't set config.json 

### ISSUE THREAD

**Issue by Aiyush-G** [retroplasma/flyover-reverse-engineering#7]
Hi, 

I really look forward to using this tool, however, the script doesn't generate the first parameter for config.json but does so for the second parameter.

I hope you can help me out, 
Cheers

**Comment by retroplasma** [comment]
Hey,

are you on macOS Big Sur? The old method doesn't work there since AFAIK GeoServices is amalgamated in some other location.

In any case please try this new method (just pushed): `./scripts/get_config.sh > config.json` which creates the config differently and also runs on Linux :)

Good luck!

**Comment by retroplasma** [comment]
Hey,

are you on macOS Big Sur? The old method doesn't work there since AFAIK GeoServices is amalgamated in some other location.

In any case please try this new method (just pushed):
```
./scripts/get_config.sh > config.json
```
It creates the config differently and also runs on Linux :)
Thanks @xde for the SDK finding which made this new method possible!

**Comment by retroplasma** [comment]
Hey,

are you on macOS Big Sur? The old method doesn't work there since AFAIK GeoServices is amalgamated in some other location.

In any case please try this new method (just pushed):
```
./scripts/get_config.sh > config.json
```
Thanks @xde for the SDK finding which made this new method possible! It creates the config differently and also runs on Linux :)

**Comment by retroplasma** [comment]
Hey,

are you on macOS Big Sur? The old method doesn't work there since AFAIK GeoServices is amalgamated in some other location.

In any case please try this new method (just pushed):
```
./scripts/get_config.sh > config.json
```
Thanks @xde for finding GeoServices in the SDK which made this new method possible! It creates the config differently and also runs on Linux :)

**Comment by Aiyush-G** [comment]
No, I'm not on BigSur yet, however, the adjustments really helped. I just had to download p7zip via home-brew to make it work.

Thanks Again
